eve:
  MONGO_HOST: "localhost"
  MONGO_PORT: 27018
  MONGO_USERNAME: "root"
  MONGO_PASSWORD: "example"
  MONGO_AUTH_SOURCE: 'admin'
  MONGO_DBNAME: "nebula"
  URL_PREFIX: ''

  PAGINATION: True
  PAGINATION_LIMIT: 200