eve:
  MONGO_HOST: "localhost"
  MONGO_PORT: 27017
  MONGO_USERNAME: ""
  MONGO_PASSWORD: ""
  MONGO_AUTH_SOURCE: 'admin'
  MONGO_DBNAME: "nebula"
  URL_PREFIX: ''

  PAGINATION: True
  PAGINATION_LIMIT: 200