eve:
  DOMAIN:
    viewed_books:
      datasource:

        source: views
        aggregation:
          pipeline: [
          {"$group": {"_id": "$doc_id", "count": {"$sum": 1}, "last_viewed": {"$max": "$at"}}}
          ]
#      doc_id: {type: string}
    books:
